# Generated by Django 6.0.6 on 2026-08-07 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('type', models.CharField(choices=[('expense', 'هزینه'), ('income', 'درآمد')], default='expense', max_length=10, verbose_name='نوع')),
                ('icon', models.CharField(default='📁', max_length=10, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'هزینه'), ('income', 'درآمد')], default='expense', max_length=10, verbose_name='نوع')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (تومان)')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.category', verbose_name='دسته')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
