# Generated by Django 6.0.6 on 2026-08-07 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'هزینه'), ('income', 'درآمد')], default='expense', max_length=10, verbose_name='نوع')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (تومان)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, verbose_name='روز ماه')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_generated', models.DateField(blank=True, null=True, verbose_name='آخرین تولید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category', verbose_name='دسته')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش تکراری',
                'verbose_name_plural': 'تراکنش\u200cهای تکراری',
                'ordering': ['active', '-created_at'],
            },
        ),
    ]
