# Generated by Django 6.0.6 on 2026-08-07 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_recurringtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon', models.CharField(default='🎯', max_length=10, verbose_name='آیکون')),
                ('target_amount', models.PositiveBigIntegerField(verbose_name='مبلغ هدف (تومان)')),
                ('saved_amount', models.PositiveBigIntegerField(default=0, verbose_name='پس\u200cانداز شده (تومان)')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='تاریخ هدف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'هدف پس\u200cانداز',
                'verbose_name_plural': 'اهداف پس\u200cانداز',
                'ordering': ['-created_at'],
            },
        ),
    ]
